import img1 from "./09d92e8a-edc6-49cc-8fb4-ce4c2822e1a7.001.jpeg"
import img2 from "./09d92e8a-edc6-49cc-8fb4-ce4c2822e1a7.002.jpeg"
import img3 from "./09d92e8a-edc6-49cc-8fb4-ce4c2822e1a7.003.jpeg"
import img4 from "./09d92e8a-edc6-49cc-8fb4-ce4c2822e1a7.004.jpeg"
const Index = () => {
  return <div>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '27pt', margin: '0pt' }}>
      <span style={{ backgroundColor: '#ffffff', fontFamily: '微軟雅黑', fontSize: '27pt', fontStyle: 'normal', fontWeight: 'bold', textTransform: 'none' }}>《葬送的芙莉蓮》：冒險結束後，回溯無法重來的旅程</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '0pt' }}>
      <span style={{ color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>&nbsp;</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>這幾年，蠻流行異世界梗的，勇者、魔王、惡龍、冒險，永遠是動漫世界的王道剛需。當《葬送的芙莉蓮》開播，我本以為這又是一</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>部熱血冒險少年番，沒想到，一個冒險故事，開局在冒險已經結束的時刻，實在是令人意外。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', margin: '16.5pt 0pt 0pt' }}>
      <img src={img1} width={640} height={852} alt="IMG_256" style={{ AwLeftPos: '0pt', AwRelHpos: 'column', AwRelVpos: 'paragraph', AwTopPos: '0pt', AwWrapType: 'inline' }} />
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '21pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>《葬送的芙莉蓮》海報</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>《葬送的芙莉蓮》原作漫畫曾獲得</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>日本漫畫大賞</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>第一名、</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>手冢治蟲文化賞</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>新生獎，系列漫畫銷量更是突破</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>800</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>萬冊，在動畫化前該作就有許多粉絲。動畫版由老牌製作公司</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>MADHOUSE</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>負責，去年話題作品《孤獨搖滾》的齋藤圭一郎擔任導演，知名動畫導演的川尻善昭參與分鏡。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>一開播，就是長達</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>2</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>小時的四集連播。動畫將一個魔法與奇幻的世界建構成熟，整體氛圍也清新自然，相當舒適。動畫版一推出就使很多觀眾感動不已。</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>勇者鬥魔王</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>的老套故事，如何俘獲了新時代的觀眾，我想是因為冒險外殼下，這是一個感傷與溫柔滿懷的治愈故事。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>勇者辛美爾、精靈芙莉蓮、僧侶海塔、矮人戰士艾澤，終於結束了十年打怪升級、懲惡揚善的冒險，封印了魔王，回到了故土。歡迎勇士們歸來的晚宴，四個戰友相談甚歡，並共賞五十年一度的流星。已經度過了千年歲月的芙莉蓮，輕易地許下</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>五十年後再相會</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>的約定，獨自踏上自己的旅程。而赴約之時，戰友們都已垂垂老矣，唯有她依然毫無變化。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>直到辛美爾壽終正寢，芙莉蓮的內心終於產生了強烈的波動：明明不過是一趟十年的</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>短暫</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>之旅，這些夥伴在她心中留下了不可磨滅的痕跡。長壽的芙莉蓮本不願對壽命短暫的種族投入太多情感，總是保持著若即若離的距離，想要避免離別的傷心，但在夥伴的死亡時才明白，沒能把握那些在一起的時光，深刻地去了解他們，才是她最後悔的事。還有很多遺憾，還有很多願望，</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>早知道</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>，這是世界上最讓人心痛的詞。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', margin: '16.5pt 0pt 0pt' }}>
      <img src={img2} width={640} height={360} alt="IMG_257" style={{ AwLeftPos: '0pt', AwRelHpos: 'column', AwRelVpos: 'paragraph', AwTopPos: '0pt', AwWrapType: 'inline' }} />
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '21pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>《葬送的芙莉蓮》劇照</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>日語裏的</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>葬送</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>二字有</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>出席葬禮、葬儀</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>等意思，《葬送的芙莉蓮》</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>——</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>送走了一個又一個同伴的芙莉蓮。我看著動畫中她立於墓前孤單的身影，覺得這個片名實在是沈重得難以直視。但告別、分離、死亡的悲傷，在這個故事中都被處理得輕盈含蓄。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>第一集就讓筆者刮目相看的是，明明是芙莉蓮與辛美爾</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>50</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>年後的再重逢，眼見曾經的少年塵滿面，鬢如霜，兩位老友的情緒卻被處理得平淡自然，直到辛美爾的死亡，才將芙莉蓮的悲傷明確地做了表達。可以說該作在情感和情緒的處理上，始終是</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>反高潮</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>反狗血</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>的。這種沈穩含蓄的表達，喜歡的人會稱贊細膩高級，但不喜歡應該就不會打開下一集了。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>其後，該作讓筆者嘆服的是，在敘事上過去與當下兩個時空的自然交織，以及在人物塑造上辛美爾與芙莉蓮隔著生死的對望。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', margin: '16.5pt 0pt 0pt' }}>
      <img src={img3} width={640} height={360} alt="IMG_258" style={{ AwLeftPos: '0pt', AwRelHpos: 'column', AwRelVpos: 'paragraph', AwTopPos: '0pt', AwWrapType: 'inline' }} />
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '21pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>《葬送的芙莉蓮》劇照</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>芙莉蓮自然是主角，但一出場就死去的辛美爾也是主角。在芙莉蓮重走過去冒險路的旅程中，辛美爾在她和夥伴的回憶、旁人的敘述中反復出現，其形象在往事中逐漸鮮明：一個勇敢、高貴、無私的勇士，一個有些幼稚、可愛、真誠的朋友。冒險的夥伴海塔會說出這樣一句話：</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>如果是辛美爾的話就會這麽做。</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>死去的辛美爾成了他們人生中的一盞燈，他們懷念這位老友，也敬重他的人品。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>而芙莉蓮當下的行走中，時不時又會講述回當初旅程中的一些細節，當時只道是尋常，而如今芙莉蓮卻往往會有醍醐灌頂的瞬間：原來當時的他，懷著這樣的溫柔心思。那些錯過的流連眼神，遺落的特別在意，都沒有隨著那個人的離開而風化，反而歷久彌新，在她記憶中煥發出新的光彩，讓她莞爾一笑，其中的感傷格外令人動容。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', margin: '16.5pt 0pt 0pt' }}>
      <img src={img4} width={640} height={360} alt="IMG_259" style={{ AwLeftPos: '0pt', AwRelHpos: 'column', AwRelVpos: 'paragraph', AwTopPos: '0pt', AwWrapType: 'inline' }} />
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '21pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>《葬送的芙莉蓮》劇照</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>動畫中也會有一些冷幽默瞬間，比如芙莉蓮帶著徒弟去見當年被封印的魔王。魔王從幾十年的沈睡中醒來，當年一招製敵的</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>殺人魔法</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>，如今卻成了</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>普通魔法</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」——</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>原來當年的</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>殺人魔法</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>在人類社會幾十年的共同研習之下，已經人人都會。這一刻，筆者和魔王一起沈默了。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>芙莉蓮的旅程，是一段凝望和回溯時間之旅，回憶和當下交織，不斷映照呼應，一個美麗的主題呼之欲出：生命有盡頭，而意義並不會隨著生命的終結而終結。如果意義會隨著個體生命的消逝而消逝，那等於對生命下了毫無意義的論斷，但實際上，個體生命的意義在友人的記憶中延續，在其一生奮鬥所澤被的大陸民眾的和平生活中延續。生命的意義，原來存在於個體生命之外的廣袤世界。</span>
    </p>
    <p style={{ backgroundColor: '#ffffff', lineHeight: '22.5pt', margin: '18pt 0pt 0pt' }}>
      <span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>芙莉蓮在旅行中，不斷尋找被遺忘和失落的魔法，很多魔法本身的用處簡直莫名其妙，堪稱毫無</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>意義</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>，但記錄、留存、傳頌，本身就是一種意義，是魔法被創造時的故事的紀念碑。生命本身，就是一場魔力十足的創造。一個看似</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>「</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>老土</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: 'Arial', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>」</span><span style={{ backgroundColor: '#ffffff', color: '#222222', fontFamily: '宋體', fontSize: '13.5pt', fontStyle: 'normal', textTransform: 'none' }}>的冒險故事，卻因其切入角度不同而有了新的觀賞價值，並傳達了更深刻溫柔的情感，《葬送的芙莉蓮》值得耐心觀看和回味。</span>
    </p>
    <p style={{ margin: '0pt', orphans: 0, textAlign: 'justify', widows: 0 }}>
      <span style={{ fontFamily: 'Calibri', fontSize: '10.5pt' }}>&nbsp;</span>
    </p>
  </div>
}

export default Index